name: Prefixes
main: com.github.neapovil.prefixes.Prefixes
version: 1.0.0
api-version: 1.19
author: Neapovil
website: https://github.com/Neapovil/prefixes
depend:
  - CommandAPI
permissions:
  prefixes.command:
    default: op
